import type {
  User,
  Site,
  Activity,
  TopSite,
  Property,
  ScraperSite,
  ActivityLog,
} from "./types";

export const mockUsers: User[] = [
  {
    id: "1",
    name: "Ethan Harper",
    email: "ethan.harper@example.com",
    role: "Admin",
    status: "Active",
    lastLogin: "2024-01-20 10:00 AM",
  },
  {
    id: "2",
    name: "Olivia Bennett",
    email: "olivia.bennett@example.com",
    role: "Editor",
    status: "Active",
    lastLogin: "2024-01-19 03:30 PM",
  },
  {
    id: "3",
    name: "Noah Carter",
    email: "noah.carter@example.com",
    role: "Viewer",
    status: "Inactive",
    lastLogin: "2024-01-18 09:15 AM",
  },
  {
    id: "4",
    name: "Ava Mitchell",
    email: "ava.mitchell@example.com",
    role: "Admin",
    status: "Active",
    lastLogin: "2024-01-17 02:45 PM",
  },
  {
    id: "5",
    name: "Liam Foster",
    email: "liam.foster@example.com",
    role: "Editor",
    status: "Active",
    lastLogin: "2024-01-16 11:00 AM",
  },
];

export const mockSites: Site[] = [
  {
    id: "1",
    name: "Site One",
    baseUrl: "https://siteone.com",
    lastRun: "2024-01-15 10:00",
    status: "Completed",
    enabled: true,
  },
  {
    id: "2",
    name: "Site Two",
    baseUrl: "https://sitetwo.com",
    lastRun: "2024-01-14 14:30",
    status: "Failed",
    enabled: false,
  },
  {
    id: "3",
    name: "Site Three",
    baseUrl: "https://sitethree.com",
    lastRun: "2024-01-16 09:15",
    status: "Running",
    enabled: true,
  },
];

export const mockScraperSites: ScraperSite[] = [
  {
    id: "1",
    name: "Site One",
    baseUrl: "https://siteone.com",
    lastRun: "2024-01-15 10:00",
    status: "Completed",
    enabled: true,
  },
  {
    id: "2",
    name: "Site Two",
    baseUrl: "https://sitetwo.com",
    lastRun: "2024-01-14 14:30",
    status: "Failed",
    enabled: false,
  },
  {
    id: "3",
    name: "Site Three",
    baseUrl: "https://sitethree.com",
    lastRun: "2024-01-16 09:15",
    status: "Running",
    enabled: true,
  },
];

export const mockActivities: Activity[] = [
  {
    id: "1",
    date: "2024-01-15 10:00 AM",
    scraper: "Property Listings",
    status: "Success",
  },
  {
    id: "2",
    date: "2024-01-15 09:30 AM",
    scraper: "Agent Profiles",
    status: "Success",
  },
  {
    id: "3",
    date: "2024-01-15 09:00 AM",
    scraper: "Neighborhood Data",
    status: "Failed",
  },
  {
    id: "4",
    date: "2024-01-14 05:00 PM",
    scraper: "Property Listings",
    status: "Success",
  },
  {
    id: "5",
    date: "2024-01-14 04:30 PM",
    scraper: "Agent Profiles",
    status: "Success",
  },
];

export const mockActivityLogs: ActivityLog[] = [
  {
    id: "1",
    date: "2024-01-15 10:00 AM",
    scraper: "Property Listings",
    status: "Success",
  },
  {
    id: "2",
    date: "2024-01-15 09:30 AM",
    scraper: "Agent Profiles",
    status: "Success",
  },
  {
    id: "3",
    date: "2024-01-15 09:00 AM",
    scraper: "Neighborhood Data",
    status: "Failed",
  },
  {
    id: "4",
    date: "2024-01-14 05:00 PM",
    scraper: "Property Listings",
    status: "Success",
  },
  {
    id: "5",
    date: "2024-01-14 04:30 PM",
    scraper: "Agent Profiles",
    status: "Success",
  },
];

export const mockTopSites: TopSite[] = [
  {
    id: "1",
    site: "Real Estate Listings",
    scraper: "Property Listings",
    records: 5234,
  },
  {
    id: "2",
    site: "Agent Finder",
    scraper: "Agent Profiles",
    records: 3456,
  },
  {
    id: "3",
    site: "Neighborhood Insights",
    scraper: "Neighborhood Data",
    records: 2134,
  },
];

export const mockProperties: Property[] = [
  {
    id: "1",
    title: "Cozy Apartment",
    price: 250000,
    pricePerSqm: 2500,
    location: "City Center",
    bedrooms: 2,
    bathrooms: 2,
    type: "Apartment",
    source: "RealEstate.com",
    timestamp: "2024-01-15 10:00",
    featured: true,
    newListing: false,
    openHouse: false,
  },
  {
    id: "2",
    title: "Spacious House",
    price: 500000,
    pricePerSqm: 1500,
    location: "Greenfield Estates",
    bedrooms: 4,
    bathrooms: 3,
    type: "House",
    source: "RealEstate.com",
    timestamp: "2024-01-15 11:30",
    featured: false,
    newListing: true,
    openHouse: false,
  },
  {
    id: "3",
    title: "Luxury Condo",
    price: 750000,
    pricePerSqm: 3000,
    location: "Coastal Heights",
    bedrooms: 3,
    bathrooms: 2,
    type: "Condo",
    source: "RealEstate.com",
    timestamp: "2024-01-15 12:45",
    featured: true,
    newListing: false,
    openHouse: true,
  },
  {
    id: "4",
    title: "Townhouse",
    price: 350000,
    pricePerSqm: 2000,
    location: "Old Town",
    bedrooms: 2,
    bathrooms: 2,
    type: "Townhouse",
    source: "RealEstate.com",
    timestamp: "2024-01-15 14:00",
    featured: false,
    newListing: false,
    openHouse: true,
  },
  {
    id: "5",
    title: "Studio Apartment",
    price: 150000,
    pricePerSqm: 3500,
    location: "Hip District",
    bedrooms: 1,
    bathrooms: 1,
    type: "Studio",
    source: "RealEstate.com",
    timestamp: "2024-01-15 15:15",
    featured: false,
    newListing: true,
    openHouse: false,
  },
  {
    id: "6",
    title: "Modern Penthouse",
    price: 1200000,
    pricePerSqm: 4000,
    location: "Downtown Heights",
    bedrooms: 3,
    bathrooms: 3,
    type: "Penthouse",
    source: "RealEstate.com",
    timestamp: "2024-01-15 16:20",
    featured: true,
    newListing: true,
    openHouse: true,
  },
  {
    id: "7",
    title: "Family Home",
    price: 425000,
    pricePerSqm: 1700,
    location: "Suburban Valley",
    bedrooms: 4,
    bathrooms: 2,
    type: "House",
    source: "RealEstate.com",
    timestamp: "2024-01-15 17:00",
    featured: false,
    newListing: false,
    openHouse: false,
  },
  {
    id: "8",
    title: "Waterfront Villa",
    price: 850000,
    pricePerSqm: 3200,
    location: "Lakeside",
    bedrooms: 5,
    bathrooms: 4,
    type: "Villa",
    source: "RealEstate.com",
    timestamp: "2024-01-15 18:15",
    featured: true,
    newListing: false,
    openHouse: false,
  },
];
